# Generated by Django 5.1.2 on 2025-01-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_telegram_id_userprofile_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_rating',
            field=models.IntegerField(default=0),
        ),
    ]
